FROM nginx
RUN rm /etc/nginx/nginx.conf
RUN rm /etc/nginx/conf.d/default.conf
COPY ./conf/ /etc/nginx
COPY ./events-dashboard/ /var/www/html/events-dashboard
COPY ./guest-dashboard/ /var/www/html/guest-dashboard
