CREATE TABLE posts_position_idx (
  id SERIAL ,
  post_id BIGINT NOT NULL,
  position BIGINT NOT NULL,
  PRIMARY KEY (id,post_id,position),
  CONSTRAINT FK_POSTS_POSITION_IDX_POST FOREIGN KEY (post_id) REFERENCES posts (id)
);

CREATE SEQUENCE POSTS_POSITION_IDX_SEQ START WITH 1 INCREMENT BY 1;